version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install

      - run:
          name: Build Application
          command: npm run build 

  publish:
    docker:
      - image: cimg/node:16.10
    requires:
      - build
    steps:
      - checkout
      - docker/check:
          docker-username: $DOCKER_USERNAME
          docker-password: $DOCKER_PASSWORD
      - run:
          name: Build and Push Image
          command: |
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker build -t 'liewchooichin/assignment4:latest' .
            docker push 'liewchooichin/assignment4:latest'
