version: 2.1

orbs:
  node: circleci/node@5.0.1
  docker: circleci/docker@1.4.0

jobs:
  build:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Install dependencies"
          npm install
  test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Running tests"
          npm run test
  publish:
    docker:
      - image: cimg/base:current
    resource_class: small
    steps:
      - checkout
      - docker/check:
          docker-username: DOCKER_USERNAME
          docker-password: DOCKER_PASSWORD
      - run: |
          echo "Building image"
          service docker status
          service docker start
          service docker status
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker build -t 'assignment4:latest' .
          docker push 'liewchooichin/assignment4:latest'

workflows:
  simple_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - publish:
          context:
            - build-env-vars
            - docker-hub-creds
          requires:
            - build
            - test

