version: 2.1
obrs:
  node: circleci/node@5.0.1 
jobs:
  publish:
    docker:
      - image: cimg/node:16.10
    steps:
      - docker/check:
          docker-username: DOCKER_USERNAME
          docker-password: DOCKER_PASSWORD
      - docker/build:
          image: liewchooichin/assignment5
      - docker/push:
          image: liewchooichin/assignment5
      - run:
          command: |
            echo "Pushing image"
workflows:
  simple-workflow:  
    jobs:
      - publish:
          context:
            - build-env-vars
            - docker-hub-creds

