version: 2.1
obrs:
  docker: circleci/docker@2.8.1
jobs:
    docker:
      - image: cimg/node:16.10
    steps:
      - docker/check:
          docker-username: DOCKER_USERNAME
          docker-password: DOCKER_PASSWORD
      - docker/build:
          image: liewchooichin/assignment5
      - docker/push:
          image: liewchooichin/assignment5
      - run:
          command: |
            echo "Pushing image"
workflows:
  my-workflow:  
    jobs:
      - machine-job:
          context:
            - build-env-vars
            - docker-hub-creds

